# This is the configuration file for Netlify
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build your Nuxt site as static HTML for Netlify
  command = "npm run generate"
  publish = "dist"
  functions = "netlify/functions"

# Enable the Netlify Visual Editor plugin
[[plugins]]
package = "@netlify/plugin-visual-editor"
``
